### ISSUE TITLE
We need more data for the chatbot

### ISSUE THREAD

**Issue by s7yby02** [AybELHARRAN/S7yby_Nutrition_Chatbot#11]
Please, everyone try his best to look for any kind of data about bodybuilding diet that includes **Meal Plans**, which should detail the quantities of protein, carbohydrates, and other nutritional elements.

**Comment by OussamaElhamdani** [comment]
Now fixed we 've augmented data including more plans and more possible answers so that the chatbot now can answers a verity of questions.

**Comment by OussamaElhamdani** [comment]
Now fixed we've augmented data including more plans and more possible answers so that the chatbot now can answers a variety of questions

**Comment by Ayasgo** [comment]
done
